### ISSUE TITLE
Isolate the Concentric CSS rules

### ISSUE THREAD

**Issue by chaucerbao** [danilobuerger/stylelint-config-concentric#2]
I notice that you import `stylelint-config-standard` and then add your Concentric CSS rules to it. Perhaps that's the goal of your project.

> Configuration rules based on stylelint-config-standard adding a concentric property sort order.

But, I'm wondering if it would be more flexible to isolate the Concentric CSS rules so that you can extend any stylelint config with Concentric CSS rules without pulling in the whole stylelint-config-standard ruleset.

**Comment by danilobuerger** [comment]
Sure, just submit a PR :-)

**Comment by danilobuerger** [comment]
Fixed with https://github.com/danilobuerger/stylelint-config-concentric/commit/aab3ff8e6e66bec5b7186f3b1186a38c68365d15
