### ISSUE TITLE
Missing transition properties

### ISSUE THREAD

**Issue by josephdburdick** [danilobuerger/stylelint-config-concentric#3]
Hi, I'm about to implement your plugin because it's perfect for my needs. I noticed that you're missing a few transition and transform properties, namely `transition-property`, `transition-duration`, `transition-timing-function`, `transition-delay`, `transform-origin`, etc. 

I'll see about making PR to address this.

**Comment by danilobuerger** [comment]
Hi @josephdburdick, thanks for the input. I will gladly look at a PR :-).
